### ISSUE TITLE
Why is there no video after detection in the GUI

### ISSUE THREAD

**Issue by a1655868410** [khaledsabry97/Argus#52]
When I use the RunCamera , why doesn't the video after the detection appear in RunGUI

**Comment by khaledsabry97** [comment]
Have you run the other backend services (RunMaster, RunDetect, RunTracker, RunCrash, RunGui) ?

**Comment by a1655868410** [comment]
Yes, I ran RunMaster, RunDetect, RunTracker, RunCrash, RunGui, and RunCamera.
Error in RunMaster: "frame_width=len(frames[0][0]) IndexError:list index out of range", printed in RunCrash: "svc object has no attribute '_probA", but this does not affect the code running. Meanwhile, the software version of requirements.txt is too low, so all the software I installed is of high version. Finally, a print of the collision situation can be seen at the terminal

**Comment by a1655868410** [comment]
"collision has occured" was printed in the terminal of "RunCrash", but nothing like "tracker_id 5 saved" was printed

**Comment by a1655868410** [comment]
Hello, I have modified my software version and can display it on the GUI interface.  However, a new problem occurred.  Only when the video I selected was an existing video on the GUI Interface "Argus-User interface", the GUI interface would display the detected video.  However, if I selected another video, the GUI interface would not display the detected video.

**Comment by a1655868410** [comment]
"collision has occured!" has been printed in the terminal of "RunCrash".  But nothing like "tracker_id 5 saved！" was printed.

**Comment by a1655868410** [comment]
Hello, I have modified the software version, and it can be displayed on the GUI interface.  However, a new problem has arisen.  Some videos can display the result of the collision in the GUI, and some can't.  For those videos that cannot display the detection result, the "collision has occured!  "has been printed in the terminal of "RunCrash",but nothing like "tracker_id 5 saved"was printed.
