### ISSUE TITLE
issues running python scripts

### ISSUE THREAD

**Issue by vhuard** [khaledsabry97/Argus#53]
i meet lots of issues with running !pip install -r requirements.txt
i forced pip install for every single version and now i am stuck since none of the Run**.py scripts is working
an example

while running RunGui.py i got the following messages
pygame 2.3.0 (SDL 2.24.2, Python 3.10.11)
Hello from the pygame community. https://www.pygame.org/contribute.html
QObject::moveToThread: Current thread (0x1f7d020) is not the object's thread (0x27afda0).
Cannot move to target thread (0x1f7d020)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.10/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

while running RunMaster.py i got the following messages
[21]
!python RunMaster.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/content/Argus/System/Database/DatabaseThread.py", line 44, in run
    frame_width = len(frames[0][0])
IndexError: list index out of range

**Comment by manishpathak99** [comment]
I am facing the same issue , did you able to solve it ?

**Comment by khaledsabry97** [comment]
I fixed the bug today... please Pull the new changes and install the requirements

pip install -r requirements.txt


if it worked with you; please reply to close the thread
